### PR TITLE
Add kwargs in run_gadget_as_app.

### PR DESCRIPTION
**Pull request by iglesias**
By the way, awesome library 🤩

### CODE REVIEW

**Comment by salt-die** [comment]
Lol, I've been meaning to do this, but I'd like to explicitly name every keyword argument and annotate them and add it to the documentation. I know it's tedious, so I can do it soon if you don't want to.

**Comment by salt-die** [comment]
Ok, I addressed this with https://github.com/salt-die/batgrl/commit/0358642d864914db5c6aa994f889b5515ce4ca30.
I'll tentatively close this. Feel free to re-open if there's something else you'd like to add.

**Comment by iglesias** [comment]
Great, thanks!

I will update locally soon and try with 0358642d864914db5c6aa994f889b5515ce4ca30.

I started looking into the library last December during the Advent of Code season and have eventually managed to use it from C++ (¯\_(ツ)_/¯). I will be pushing some of that into my fork soon. I am finding it a pleasure to work with, very readable and cool visuals.

**Comment by salt-die** [comment]
> ... managed to use it from C++ (¯_(ツ)_/¯). 

That's really cool! I'd love to see that!

**Comment by iglesias** [comment]
Nice! [Here](https://github.com/salt-die/batgrl/compare/main...iglesias:batgrl:cpp#diff-eb23192e3a3815c3b93b810acee564b0c440a9654c1087acd2607cfd9518f14f) is an example and [how it looks](https://www.reddit.com/r/adventofcode/comments/1ety82f/2021_day_11/).

The visuals I have been doing (this one, another with 3d cubes, and a random rock paper scissors) are simple I'd say. Most of it so far has been the async part, which has turned out to be nice to learn about C++20 coroutines and cool to eventually get to syntax like `co_await [some asyncio fn / async def];`.

**Pull request closed without merging**
